# Generated by Django 4.2.4 on 2023-08-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "valor_pedido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor do Pedido",
                    ),
                ),
                (
                    "valor_boy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor do Boy",
                    ),
                ),
                (
                    "pedido_pago",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Pedido Pago"
                    ),
                ),
                (
                    "motoboy_pago",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Motoboy Pago",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Rua"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Numero"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="UF"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_CotacaoEntregas.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Endereços",
                "db_table": "endereco",
            },
        ),
    ]
