# Generated by Django 4.2.4 on 2023-08-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CotacaoEntregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
