# Generated by Django 4.2.4 on 2023-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_CotacaoEntregas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="n_pedido",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome"
            ),
        ),
    ]
