# Generated by Django 4.2.4 on 2023-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_CotacaoEntregas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="descricao",
        ),
        migrations.AddField(
            model_name="endereco",
            name="infor_adicional",
            field=models.TextField(
                blank=True, null=True, verbose_name="Informações adicionais"
            ),
        ),
    ]
