# Generated by Django 4.2.4 on 2023-08-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CotacaoEntregas', '0002_cliente_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='motoboy_pago',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Motoboy Pago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pedido_pago',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pedido Pago'),
        ),
    ]
