# Generated by Django 4.2.4 on 2023-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CotacaoEntregas', '0004_endereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Cep'),
        ),
    ]
