# Generated by Django 4.2.4 on 2023-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CotacaoEntregas', '0005_endereco_complemento_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
    ]
